# Data Cleaning - Locations_saisonnière Location Marrakech
This notebook focuses on cleaning the locations_saisonnière location data for Marrakech.

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# File path
file_path = '../../data/marrakech_immo_location/locations_saisonniere_location.csv'

# Load data
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print(f"Successfully loaded {file_path}")
    display(df.head())
else:
    print(f"ERROR: File not found at {file_path}")
    print(f"Current working directory: {os.getcwd()}")

Successfully loaded ../../data/marrakech_immo_location/locations_saisonniere_location.csv

,id,titre,prix,localisation,type_bien,surface,chambres,salles_bain,description,agence,...,etage,surface_terrain,prix_num,surface_num,chambres_num,salles_bain_num,nb_pieces,quartier,prix_m2,prix_m2_median_quartier
0,LOM25328,APPARTEMENT 2 CHAMBRES A LA PALMERAIE,1 200 Dhs / nuit,Marrakech,Locations saisonnières,73 m²,2.0,NaN,Ce charmant appartement situé au sein du prest...,Marrakech Realty,...,-1,NaN,1200.0,73.0,2.0,0.0,3.0,Autre,16.438356,16.552511
1,LOV26002,Magnifique Rez-de-Jardin à Prestigia – Idéal F...,1 500 Dhs / nuit,Marrakech,Locations saisonnières,90 m²,NaN,NaN,"Ce spacieux appartement en rez-de-jardin, situ...",Marrakech Realty,...,-1,NaN,1500.0,90.0,0.0,0.0,1.0,Autre,16.666667,16.552511
2,RCD1,Riad Ker 46 – Médina – 3 chambres – Terrasse a...,1760-2200 Dhs / nuit,Marrakech,Locations saisonnières,m²,3.0,NaN,"Bienvenue au riad Ker46, à deux pas de la plac...",Marrakech Realty,...,-1,NaN,17602200.0,NaN,3.0,0.0,4.0,Autre,NaN,16.552511
3,RCD2,Riad Ker 47 – 4 chambres – Terrasse avec vue s...,2145-2640 Dhs / nuit,Marrakech,Locations saisonnières,m²,4.0,NaN,"A deux pas de la Place Jemma el Fna, ses atout...",Marrakech Realty,...,-1,NaN,21452640.0,NaN,4.0,0.0,5.0,Autre,NaN,16.552511
4,RCD4,Riad Le Loft – 3 chambres – Médina Marrakech,2200 - 3850 Dhs / nuit,Marrakech,Locations saisonnières,m²,3.0,NaN,"L'emplacement : Très bien placé en médina, dan...",Marrakech Realty,...,-1,NaN,22003850.0,NaN,3.0,0.0,4.0,Autre,NaN,16.552511

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       9 non-null      str
 1   titre                    9 non-null      str
 2   prix                     9 non-null      str
 3   localisation             9 non-null      str
 4   type_bien                9 non-null      str
 5   surface                  9 non-null      str
 6   chambres                 7 non-null      float64
 7   salles_bain              0 non-null      float64
 8   description              9 non-null      str
 9   agence                   9 non-null      str
 10  url                      9 non-null      str
 11  source                   9 non-null      str
 12  piscine                  9 non-null      int64
 13  parking                  9 non-null      int64
 14  ascenseur                9 non-null      int64
 15  terrasse                 9 non-null      int64
 16  jardin                   9 non-null      int64
 17  climatisation            9 non-null      int64
 18  securite                 9 non-null      int64
 19  vue                      9 non-null      int64
 20  meuble                   9 non-null      int64
 21  neuf                     9 non-null      int64
 22  cave                     9 non-null      int64
 23  hammam                   9 non-null      int64
 24  etage                    9 non-null      int64
 25  surface_terrain          0 non-null      float64
 26  prix_num                 9 non-null      float64
 27  surface_num              2 non-null      float64
 28  chambres_num             9 non-null      float64
 29  salles_bain_num          9 non-null      float64
 30  nb_pieces                9 non-null      float64
 31  quartier                 9 non-null      str
 32  prix_m2                  2 non-null      float64
 33  prix_m2_median_quartier  9 non-null      float64
dtypes: float64(10), int64(13), str(11)
memory usage: 2.5 KB

In [8]:
df.describe()

,chambres,salles_bain,piscine,parking,ascenseur,terrasse,jardin,climatisation,securite,vue,...,hammam,etage,surface_terrain,prix_num,surface_num,chambres_num,salles_bain_num,nb_pieces,prix_m2,prix_m2_median_quartier
count,7.000000,0.0,9.000000,9.000000,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.0,0.0,9.000000e+00,2.000000,9.000000,9.0,9.000000,2.000000,9.000000
mean,3.285714,NaN,0.555556,0.222222,0.0,0.777778,0.444444,0.222222,0.111111,0.222222,...,0.222222,-1.0,NaN,2.106883e+07,81.500000,2.555556,0.0,3.555556,16.552511,16.552511
std,0.755929,NaN,0.527046,0.440959,0.0,0.440959,0.527046,0.440959,0.333333,0.440959,...,0.440959,0.0,NaN,1.403861e+07,12.020815,1.589899,0.0,1.589899,0.161440,0.000000
min,2.000000,NaN,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-1.0,NaN,1.200000e+03,73.000000,0.000000,0.0,1.000000,16.438356,16.552511
25%,3.000000,NaN,0.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-1.0,NaN,1.760220e+07,77.250000,2.000000,0.0,3.000000,16.495434,16.552511
50%,3.000000,NaN,1.000000,0.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,-1.0,NaN,2.200385e+07,81.500000,3.000000,0.0,4.000000,16.552511,16.552511
75%,4.000000,NaN,1.000000,0.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,-1.0,NaN,2.800385e+07,85.750000,4.000000,0.0,5.000000,16.609589,16.552511
max,4.000000,NaN,1.000000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,-1.0,NaN,4.389539e+07,90.000000,4.000000,0.0,5.000000,16.666667,16.552511

In [9]:
df.columns

Index(['id', 'titre', 'prix', 'localisation', 'type_bien', 'surface',
       'chambres', 'salles_bain', 'description', 'agence', 'url', 'source',
       'piscine', 'parking', 'ascenseur', 'terrasse', 'jardin',
       'climatisation', 'securite', 'vue', 'meuble', 'neuf', 'cave', 'hammam',
       'etage', 'surface_terrain', 'prix_num', 'surface_num', 'chambres_num',
       'salles_bain_num', 'nb_pieces', 'quartier', 'prix_m2',
       'prix_m2_median_quartier'],
      dtype='str')

In [10]:
df.shape

(9, 34)

## 1. Initial Data Overview

In [11]:
if 'df' in locals():
    print("Shape:", df.shape)
    df.info()
else:
    print("DataFrame 'df' not loaded. Please fix the file path above.")

Shape: (9, 34)
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 34 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       9 non-null      str
 1   titre                    9 non-null      str
 2   prix                     9 non-null      str
 3   localisation             9 non-null      str
 4   type_bien                9 non-null      str
 5   surface                  9 non-null      str
 6   chambres                 7 non-null      float64
 7   salles_bain              0 non-null      float64
 8   description              9 non-null      str
 9   agence                   9 non-null      str
 10  url                      9 non-null      str
 11  source                   9 non-null      str
 12  piscine                  9 non-null      int64
 13  parking                  9 non-null      int64
 14  ascenseur                9 non-null      int64
 15  terrasse                 9 non-null      int64
 16  jardin                   9 non-null      int64
 17  climatisation            9 non-null      int64
 18  securite                 9 non-null      int64
 19  vue                      9 non-null      int64
 20  meuble                   9 non-null      int64
 21  neuf                     9 non-null      int64
 22  cave                     9 non-null      int64
 23  hammam                   9 non-null      int64
 24  etage                    9 non-null      int64
 25  surface_terrain          0 non-null      float64
 26  prix_num                 9 non-null      float64
 27  surface_num              2 non-null      float64
 28  chambres_num             9 non-null      float64
 29  salles_bain_num          9 non-null      float64
 30  nb_pieces                9 non-null      float64
 31  quartier                 9 non-null      str
 32  prix_m2                  2 non-null      float64
 33  prix_m2_median_quartier  9 non-null      float64
dtypes: float64(10), int64(13), str(11)
memory usage: 2.5 KB

## 2. Handling Missing Values

In [12]:
if 'df' in locals():
    # Checking for null values
    null_counts = df.isnull().sum()
    print("Columns with null values before cleaning:")
    print(null_counts[null_counts > 0])
    
    # 1. Variables numériques : imputation par la médiane
    num_cols_to_fill = ['prix_num', 'surface_num', 'prix_m2', 'prix_m2_median_quartier']
    for col in num_cols_to_fill:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].median())
            
    # 2. Variables catégorielles : imputation par le mode (valeur la plus fréquente)
    cat_cols_mode = ['agence', 'type_bien', 'localisation']
    for col in cat_cols_mode:
        if col in df.columns:
            mode_val = df[col].mode()
            if not mode_val.empty:
                df[col] = df[col].fillna(mode_val[0])
            
    # 3. Champs texte : on met 'Non spécifié'
    text_cols = ['titre', 'description', 'prix', 'surface', 'url']
    for col in text_cols:
        if col in df.columns:
            df[col] = df[col].fillna('Non spécifié')
    
    # 4. Traitement des chambres et salles de bain
    non_residential = ['terrain', 'locaux', 'commercial', 'bureaux']
    if 'locations_saisonnière' in non_residential:
        if 'chambres_num' in df.columns: df['chambres_num'] = df['chambres_num'].fillna(0.0)
        if 'chambres' in df.columns: df['chambres'] = df['chambres'].fillna('0')
        if 'salles_bain_num' in df.columns: df['salles_bain_num'] = df['salles_bain_num'].fillna(0.0)
        if 'salles_bain' in df.columns: df['salles_bain'] = df['salles_bain'].fillna('0')
    else:
        if 'chambres_num' in df.columns and not df['chambres_num'].isnull().all():
            mean_ch = round(df['chambres_num'].mean())
            df['chambres_num'] = df['chambres_num'].fillna(mean_ch)
            if 'chambres' in df.columns: df['chambres'] = df['chambres'].fillna(str(int(mean_ch)))
        if 'salles_bain_num' in df.columns and not df['salles_bain_num'].isnull().all():
            mean_sb = round(df['salles_bain_num'].mean())
            df['salles_bain_num'] = df['salles_bain_num'].fillna(mean_sb)
            if 'salles_bain' in df.columns: df['salles_bain'] = df['salles_bain'].fillna(str(int(mean_sb)))
    # 5. Traitement de la surface du terrain
    if '{property_type}' in ['appartement', 'studio', 'duplex']:
        if 'surface_terrain' in df.columns: df['surface_terrain'] = df['surface_terrain'].fillna(0.0)
    else:
        if 'surface_terrain' in df.columns and 'surface_num' in df.columns:
            df['surface_terrain'] = df['surface_terrain'].fillna(df['surface_num'])
    
    # id: on supprime les lignes sans ID car c'est crucial
    if 'id' in df.columns:
        df.dropna(subset=['id'], inplace=True)
        
    print("\nColumns with null values after cleaning:")
    print(df.isnull().sum()[df.isnull().sum() > 0])

Columns with null values before cleaning:
chambres           2
salles_bain        9
surface_terrain    9
surface_num        7
prix_m2            7
dtype: int64

Columns with null values after cleaning:
Series([], dtype: int64)

## 3. Removing Duplicates

In [13]:
if 'df' in locals():
    initial_size = len(df)
    df = df.drop_duplicates()
    print(f"Removed {initial_size - len(df)} duplicate rows.")

Removed 0 duplicate rows.

## 4. Cleaning Numerical Columns
Handling outliers for price and surface.

In [14]:
if 'df' in locals():
    if 'prix_num' in df.columns:
        q_low = df['prix_num'].quantile(0.01)
        q_hi  = df['prix_num'].quantile(0.99)
        df = df[(df['prix_num'] <= q_hi) & (df['prix_num'] >= q_low)]
        print(f"Data points after price outlier removal: {len(df)}")
    
    if 'surface_num' in df.columns:
        q_low_surf = df['surface_num'].quantile(0.01)
        q_hi_surf  = df['surface_num'].quantile(0.99)
        df = df[(df['surface_num'] <= q_hi_surf) & (df['surface_num'] >= q_low_surf)]
        print(f"Data points after surface outlier removal: {len(df)}")

Data points after price outlier removal: 7
Data points after surface outlier removal: 6

## 5. Saving Cleaned Data

In [15]:
if 'df' in locals():
    output_dir = '../../data/cleaned_data/location'
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    output_file = 'locations_saisonniere_location_cleaned.csv'
    output_path = os.path.join(output_dir, output_file)
    df.to_csv(output_path, index=False)
    print(f"Cleaned data saved to {output_path}")

Cleaned data saved to ../../data/cleaned_data/location/locations_saisonniere_location_cleaned.csv